// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2QKHy64AA7qibzVaMTrPaHflU5ptJH78',
    appId: '1:556045063093:web:9a7e510880a9a5d43d3ffc',
    messagingSenderId: '556045063093',
    projectId: 'rosy-precinct-393019',
    authDomain: 'rosy-precinct-393019.firebaseapp.com',
    storageBucket: 'rosy-precinct-393019.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA12SNG4YUXFehW7eu-vmhBRYQHhB9rs9o',
    appId: '1:556045063093:android:532a50d51fe801df3d3ffc',
    messagingSenderId: '556045063093',
    projectId: 'rosy-precinct-393019',
    storageBucket: 'rosy-precinct-393019.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbvzFvNdd6bFJwQzUopQ9tHnQuZRqCNFY',
    appId: '1:556045063093:ios:e9c0f0a9d488db293d3ffc',
    messagingSenderId: '556045063093',
    projectId: 'rosy-precinct-393019',
    storageBucket: 'rosy-precinct-393019.firebasestorage.app',
    iosClientId: '556045063093-a4c3pcj973givn2d3tr6rpn143g35np3.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationalTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbvzFvNdd6bFJwQzUopQ9tHnQuZRqCNFY',
    appId: '1:556045063093:ios:e9c0f0a9d488db293d3ffc',
    messagingSenderId: '556045063093',
    projectId: 'rosy-precinct-393019',
    storageBucket: 'rosy-precinct-393019.firebasestorage.app',
    iosClientId: '556045063093-a4c3pcj973givn2d3tr6rpn143g35np3.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationalTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2QKHy64AA7qibzVaMTrPaHflU5ptJH78',
    appId: '1:556045063093:web:65181f360cd573f33d3ffc',
    messagingSenderId: '556045063093',
    projectId: 'rosy-precinct-393019',
    authDomain: 'rosy-precinct-393019.firebaseapp.com',
    storageBucket: 'rosy-precinct-393019.firebasestorage.app',
  );
}
